################################################################################
#1.Setup

### Restart R
#.rs.restartR()

### Start with a clean environment by removing objects in workspace
rm(list=ls())

### Setting work directory
working_directory <- base::setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
#working_directory <- base::setwd(".")

### Load Rdata
Rdata_files <- list.files(path = working_directory, pattern = "*.RData", full.names = T)

if ( length(Rdata_files) >0) {
  invisible(lapply(Rdata_files,load,.GlobalEnv))
} else {
  paste(c(".RData files", "do not exist"), collapse = " ")
}

### Install required packages
source("./1.setup/requirements.R")

### helper/customized functions
source("./1.setup/helperfuns_gt_summary_themes.R")
source("./1.setup/helperfuns_ggplot_themes.R")

################################################################################

### Load data 
source("./2.data_processing/load_data_local.R")

### Load recode file
source("./2.data_processing/load_data_dictionary_file.R")

### Data cleaning
source("./2.data_processing/cleaning.R")

### Descriptive stats
source("./2.data_processing/descriptive_stats.R")

### Save stats output
source("./2.data_processing/save_descriptive_output.R")

################################################################################

# 3.Scan report 
## Generate Scan Report in WHITE RABBIT using csv "sample_data_final.csv" generated in data_processing step
## Retrieve "sample_data_final.csv" saved in output folder
## Before running the scan report, set working directory to "3.scan_report" folder

################################################################################

#4.Source code list
## Create a SOURCE CODE LIST from either SCAN Report Generated or using your own generated descriptive output

################################################################################

#5.Usagi Concept
## Source code list are loaded into USAGI to map source codes into the OMOP Vocabulary (standard terminologies)
## Export final map generated by USAGI into the OMOP Vocabulary’s SOURCE_TO_CONCEPT_MAP and "5.usagi_concept" folder

## Load saved Usagi Vocabulary Mapping file
source("./5.usagi_concept/load_usagi_mapping_local.R")

################################################################################

#6.Mapping Source to CDM
## Open scanned results from WHITE RABBIT into RABBIT-IN-A-HAT; interface displays source tables and CDM tables
## Connect source tables to CDM tables where the source table provides information for that corresponding CDM table
## For each source table to CDM table connection, further define the connection with source column to CDM column detail
## Save Rabbit-In-a-Hat work and export to a MS Word document.
## Rabbit-In-a-Hat generates documentation for the ETL process it does not generate code to create an ETL

################################################################################

#7.ETL-TO-OMOP

#file.edit("~/.Renviron") store password credentials for postgres in .Renviron and retrieve with Sys.getenv()
#usethis::edit_r_environ()
#restart R

## First Create a database in postgres named "omop_training"
database_name <- "omop_training"

## Connect to default postgres database
con <- dbConnect(
  drv = RPostgres::Postgres(),
  dbname = "postgres",
  host = "localhost",
  port = 5432,
  user = "postgres",
  password = Sys.getenv("postgres_password")
)

print(con)

source("./7.etl_to_omop/create_database.R")

dbDisconnect(con)

## Connect to "omop_training" database

con <- dbConnect(drv = RPostgres::Postgres(),
                 dbname = database_name, 
                 host = 'localhost', 
                 port = 5432, 
                 user = 'postgres',
                 password = Sys.getenv("postgres_password")
                 )

print(con)
#DBI::dbDisconnect(con)

cdm_schema_name <- "nids_cdm" 
results_schema_name <- "nids_results"
vocabulary_schema_name <- "vocabulary"

## Create OMOP-CDM Schemas for individual studies, single vocabulary and list all schemas
### Schemas are created in lower case letters. 
source("./7.etl_to_omop/create_cdm_vocab_results_schema.R")

## List all schemas after each schema have been created 
list_all_schemas_cdm <- dbGetQuery(con, "SELECT schema_name FROM information_schema.schemata") #output is df

list_all_schemas_cdm


## create OMOPCDM_5.4_ddl tables, Primary key, foreign keys and indexing
source("./7.etl_to_omop/create_cdm_tables_rpackage.R")

## Loading vocabularies in vocabulary schema

### using back slash as we are utilizing sql statements to load athena vocabs from csv files
vocab_folder_path <- glue::glue("D:\\APHRC\\OMOP-CDM\\Usagi and Vocabulary\\vocabulary_download_v5_1788964799658")


empty_vocab_tables <- FALSE #TRUE to empty and load/reload vocabularies, FALSE to do nothing

if (empty_vocab_tables) {
  
  source("./7.etl_to_omop/empty_omop_vocabs.R")
  
  #Load ATHENA vocabs from CSV
  source("./7.etl_to_omop/load_omop_vocabs.R")
}

## Transforming data from Staging and loading to OMOP-CDM

### location table
source("./7.etl_to_omop/location_to_omop.R")

### Caresite table
source("./7.etl_to_omop/caresite_to_omop.R")

### Provider table
source("./7.etl_to_omop/provider_to_omop.R")

### Person table
source("./7.etl_to_omop/person_to_omop.R")

### Visit occurrence table
source("./7.etl_to_omop/visit_occurrence_to_omop.R")

### Visit detail table
source("./7.etl_to_omop/visit_detail_to_omop.R")

### Observation period table
source("./7.etl_to_omop/observation_period_to_omop.R")

### Measurement table
source("./7.etl_to_omop/measurement_to_omop.R")

### Observation table
source("./7.etl_to_omop/observation_to_omop.R")

### Condition Occurence table
source("./7.etl_to_omop/condition_occurrence_to_omop.R")

### Condition Era table
source("./7.etl_to_omop/condition_era_to_omop.R")

### CDM Source table
source("./7.etl_to_omop/cdm_source_to_omop.R")

### Disconnecting from database
DBI::dbDisconnect(con)

################################################################################

#8.Data Quality Dashboard
source("./8.dqd/data_quality_dashboard.R")

#INSPECT LOGS

ParallelLogger::launchLogViewer(logFileName = base::file.path(DQD_Dir, "log_DqDashboard_.txt")
                                )

#VIEW RESULTS
#Launching Dashboard as Shiny App
DataQualityDashboard::viewDqDashboard(base::file.path(DQD_Dir, "results.json"))


################################################################################

#9.Achilles Characterization
source("./9.achilles_results/achilles_analysis.R")

################################################################################

#10. Atlas Analysis
## Installation and Configuration Guide: WSL, Docker, OHDSI Broadsea, PgAdmin Container, and ATLAS WebAPI

################################################################################

## Save workspace at the end without working directory path

save(list = ls(all.names = TRUE)[!ls(all.names = TRUE) %in% c("working_directory", "mainDir", "data_Dir", "output_Dir"
                                                              ,"Rdata_files", "executeDDL_Error_Dir", "Achilles_Analysis_Dir"
                                                              , "DQD_Dir", "con", "cd_dqd", "cd_achilles"
                                                              )],
     file = "nids_omop.RData",
     envir = .GlobalEnv #parent.frame()
     )

################################################################################

## Run all files in Rstudio
source("main.R")

################################################################################

